### ISSUE TITLE
Add to Chocolatey

### ISSUE THREAD

**Issue by TerribleDev** [bloomberg/collectdwin#1]
Please add this project to the Chocolatey Repository (apt-get for windows)

**Comment by yogeswaran** [comment]
I have not used Chocoltey before, can you recommend any document on how to add a project to Chocolatey repo?

**Comment by cdhunt** [comment]
https://github.com/chocolatey/choco/wiki/CreatePackages

**Comment by kkzinger** [comment]
Hi, I pushed a chocolatey Package to the main package feed. https://chocolatey.org/packages/collectdwin/0.5.8
Currently it is running through the reviewing process. Due to the fact that this is my first chocolatey package it could take a day or two till i fixed my stuff on the package and get it reviewd successfully.

**Update**: Package was reviewed and is listed now.

**Comment by kkzinger** [comment]
@yogeswaran This can be closed. I am maintaining the package at the moment.

**Comment by yogeswaran** [comment]
ok thanks @kkzinger
