### ISSUE TITLE
Console Output

### ISSUE THREAD

**Issue by kkzinger** [bloomberg/collectdwin#29]
Hi,

I am not sure how I can get the console output. Can you give me a hint how to enable get the console output from the service.
At the moment I want to setup my configuration at the host because I have no external data sink available.

regards,
Gerold

**Comment by yogeswaran** [comment]
Gerold,

1) Enable Console plugin in CollectdWin.config 
2) From command line window, pass "console" as an argument to the executable. For example:
   c:\Program Files\Bloomberg LP\CollectdWin\CollectdWinService.exe" console

-yoga   

reply@reply.github.com At: Mar  7 2016 04:02:21" data-digest="From: reply@reply.github.com At: Mar  7 2016 04:02:21" style="">
From: reply@reply.github.com At: Mar  7 2016 04:02:21
To: collectdwin@noreply.github.com
Subject: Re:[collectdwin] Console Output (#29)

Hi,  
I am not sure how I can get the console output. Can you give me a hint how to enable get the console output from the service.
At the moment I want to setup my configuration at the host because I have no external data sink available.  
regards,
Gerold

**Comment by kkzinger** [comment]
Thank you,
works as expected.

kind regards,
Gerold
